### ISSUE TITLE
Why does gocelery use BLPOP command in redis broker?

### ISSUE THREAD

**Issue by actumn** [gocelery/gocelery#123]
Hi.  
I have the question about redis_broker.go
https://github.com/gocelery/gocelery/blob/17631e11026a63f12751d8b4b0e0e2fe521e745b/redis_broker.go#L49-L83
We can find that it uses LPUSH when it sends and BLPOP when it gets.  
I assume it would be LIFO, not FIFO.  
I want to ask why it doesn't uses BRPOP which kombu uses.

https://github.com/celery/kombu/blob/8a974955a80b94eb0c7138a6cba5b53dd3dc911a/kombu/transport/redis.py#L587-L598

**Comment by sickyoon** [comment]
@actumn do you happen to be in korea? would you like to collaborate?

**Comment by actumn** [comment]
@sickyoon Yes I am :)

**Comment by sickyoon** [comment]
add me on telegram @sickyoon

**Comment by sickyoon** [comment]
It may have to do with Celery versions. Please check with `MONITOR` to see the difference between Celery versions.

**Comment by actumn** [comment]
I checked celery:3.1.25 and celery:4.0.2 with docker and I found they all use LPUSH and BRPOP. Also following the codes history in kombu, it has never changed.

**Comment by danielchengml** [comment]
@sickyoon I am using this library for my task queue and also noticed that it is behaving like a stack where the most recent task gets prioritized causing earlier tasks to stay at the bottom of the stack. 
Redis documents this very nicely where in order to achieve a queue-like behaviour, `RPUSH` is used with `LPOP` or `LPUSH` with `RPOP`. In our case @actumn suggested the latter.

ref: https://redis.io/commands/lpop

**Comment by sickyoon** [comment]
sorry @danielchengml , I've been busy with work lately.
thanks for the PR @actumn
